targets:
  - 4.6.0.13-aarch64

rpms: RPMS

shallow_clones: 1

repositories:
  - https://repo.sailfishos.org/obs/sailfishos:/chum:/testing/@VERSION@_@ARCH@/
  - https://repo.sailfishos.org/obs/nemo:/devel:/hw:/native-common/sailfish_latest_@ARCH@/
